# Generated by Django 3.2.13 on 2022-11-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='profile_path',
        ),
    ]
